# Data sources

World Happiness Report is a publication of the United Nations Sustainable Development Solutions Network. Our [dataset](https://worldhappiness.report/ed/2021/#appendices-and-data) is taken from their latest release in March, 2021 .

Life Ladder is used as the measurement of happiness in our analysis. It is the national average response to the question of life evaluations collected by the Gallup World Poll, covering years from 2008 to 2020, which is a numerical value ranging from 0 to 10 with 0 being at the bottom and 10 at the top. Values are missing for several countries from time to time due to inability to collect. We’ve landed with 1732 records in total and an average of 133 countries’ records per year. 

Below are some factors related to happiness for later analysis. More detailed descriptions of the specific wording of survey questions can be found from our source's [appendix](https://happiness-report.s3.amazonaws.com/2021/Appendix1WHR2021C2.pdf). 
```{r, echo=FALSE, results='asis'}
DataDescription<- readr::read_csv(here::here("./data_description.csv"))
knitr::kable(DataDescription[1:11,1:3 ], caption = "Factors Related to Happiness",
             row.names = F,font_size = 12)
```



For group analysis, we also obtained data from the [World Bank](https://datahelpdesk.worldbank.org/knowledgebase/articles/906519-world-bank-country-and-lending-groups) for classifications of countries as developing or developed; as well as data from International [Telecommunications Union](https://www.itu.int/en/ITU-D/Statistics/Pages/definitions/regions.aspx) that classifies the world into eight regions: Europe, Middle east, Asia & Pacific, South/Latin America, Africa, North America, Arab States.
