--- 
title: "World-Happiness-Analysis"
author: "Yanyun Chen, Siqin Shen, Yinghao Li"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

With the ongoing COVID-19 pandemic, people's mental health deserves attention more than ever. One of the most direct ways to evaluate a country's well-being is to survey citizens about how they feel about their life - are they happy about how their life? Then one question emerges, which is that what factor, in a macro perspective, such as GDP or life expectancy, shapes peoples' perception of happiness. Also, it is natural to further think about how people's happiness have changed over the past years. Is life getting better or worse than 10 years ago? Besides the subjective evaluation from every single person, we also look at the external factors that have affected the happiness score performance. 
The lifestyle or culture generally varies from continent to continent, and the GDP also determines the development level for a country. Then, there should be some correlation between happiness score and continent/development level, and this correlation is awaiting to be solved. Moreover, we shall never neglect the influence of COVID-19. The COVID-19 pandemic has been the most consequential global event in the past few years, and it inevitably brings impact on every facet of our daily life. Our mission is to explore the COVID-19 impact on the happiness score, whether it is good or bad, happy or sad. 

In this project, we gather life ladder data and other objective measurements of a country's welfare data mainly from the World Health Organization (WHO). It includes data across the world over the past years. We will focus on visualizing the score changing trend and distribution among the world, as well as carrying out practical analysis about how COVID-19 has reshaped people's perception of happiness. To be more specific, we are going to explore the data both from time and from geographic perspectives, and figure out what aspect affects people's feelings about happiness. Meanwhile, we shall also concentrate on the impact that COVID-19 brings to life. We will answer the following questions step by step in this project:

- What is the most important factor affecting the life ladder (i.e., the happiness score)? Do importance of these factors change over time?

- How did COVID-19 affect the life ladder? Would it be different across continents/development levels?

- What is the trend of the life ladder? Would it be different across continents/development levels? 

In the following chapters, we will discuss the above questions in depth with comprehensible visualizations.

For more details of this project, click the link here or copy the url https://github.com/yinghao11/World-Happiness-Analysis and open it in browser to go to our Github repository and navigate code in .Rmd files.
